In [1]:
import pandas as pd
import numpy as np

In [2]:
delivery = pd.read_csv(r"C:\Users\hp\Downloads\Practice csv files\Restaurent_Profitability_Project\delivery.csv")

In [3]:
operating_cost = pd.read_csv(r"C:\Users\hp\Downloads\Practice csv files\Restaurent_Profitability_Project\operating_costs.csv")

In [4]:
order_items = pd.read_csv(r"C:\Users\hp\Downloads\Practice csv files\Restaurent_Profitability_Project\order_items.csv")

In [5]:
orders = pd.read_csv(r"C:\Users\hp\Downloads\Practice csv files\Restaurent_Profitability_Project\orders.csv")

In [6]:
branches = pd.read_csv(r"C:\Users\hp\Downloads\Practice csv files\Restaurent_Profitability_Project\branches.csv")

In [7]:
customers = pd.read_csv(r"C:\Users\hp\Downloads\Practice csv files\Restaurent_Profitability_Project\customers.csv")

In [8]:
product = pd.read_csv(r"C:\Users\hp\Downloads\Practice csv files\Restaurent_Profitability_Project\products.csv")

In [9]:
delivery.head()

,delivery_id,order_id,delivery_partner,delivery_fee,delivery_commission,packaging_cost,delivery_distance_km,delivery_time_minutes,delivery_status
0,D000001,O000002,Partner B,42.93,42.50,25.80,5.32,31.0,Delivered
1,D000002,O000003,Partner A,32.82,75.48,21.88,3.30,39.0,Delivered
2,D000003,O000004,Partner B,31.97,210.03,24.30,10.85,26.0,Delivered
3,D000004,O000006,Partner A,79.11,99.60,9.77,3.15,37.0,Delivered
4,D000005,O000009,Partner A,33.07,117.84,15.39,5.90,41.0,Failed

In [10]:
delivery.columns

Index(['delivery_id', 'order_id', 'delivery_partner', 'delivery_fee',
       'delivery_commission', 'packaging_cost', 'delivery_distance_km',
       'delivery_time_minutes', 'delivery_status'],
      dtype='object')

In [11]:
delivery.shape

(100000, 9)

In [12]:
delivery.dtypes

delivery_id               object
order_id                  object
delivery_partner          object
delivery_fee             float64
delivery_commission      float64
packaging_cost           float64
delivery_distance_km     float64
delivery_time_minutes    float64
delivery_status           object
dtype: object

In [13]:
delivery.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   delivery_id            100000 non-null  object
 1   order_id               100000 non-null  object
 2   delivery_partner       100000 non-null  object
 3   delivery_fee           100000 non-null  float64
 4   delivery_commission    100000 non-null  float64
 5   packaging_cost         99750 non-null   float64
 6   delivery_distance_km   100000 non-null  float64
 7   delivery_time_minutes  100000 non-null  float64
 8   delivery_status        100000 non-null  object
dtypes: float64(5), object(4)
memory usage: 6.9+ MB

In [14]:
delivery.isnull().sum()

delivery_id                0
order_id                   0
delivery_partner           0
delivery_fee               0
delivery_commission        0
packaging_cost           250
delivery_distance_km       0
delivery_time_minutes      0
delivery_status            0
dtype: int64

In [15]:
delivery.nunique()

delivery_id              100000
order_id                 100000
delivery_partner              3
delivery_fee               6001
delivery_commission       25425
packaging_cost             2001
delivery_distance_km       2034
delivery_time_minutes        62
delivery_status               3
dtype: int64

In [16]:
delivery["packaging_cost"].head()

0    25.80
1    21.88
2    24.30
3     9.77
4    15.39
Name: packaging_cost, dtype: float64

In [17]:
delivery["packaging_cost"].describe()

count    99750.000000
mean        18.022197
std          5.766115
min          8.000000
25%         13.050000
50%         18.030000
75%         23.010000
max         28.000000
Name: packaging_cost, dtype: float64

In [18]:
operating_cost.head()

   cost_id branch_id   cost_date         cost_category  cost_amount
0  OC00000       B05  2025-08-08                  Rent     15269.23
1  OC00001       B02  2025-08-04          Staff Salary     22221.08
2  OC00002       B01  2026-01-06          Staff Salary     31968.32
3  OC00003       B07  2025-03-03  Other Operating Cost      5743.98
4  OC00004       B05  2026-12-07             Utilities      5214.73

In [19]:
operating_cost.columns

Index(['cost_id', 'branch_id', 'cost_date', 'cost_category', 'cost_amount'], dtype='object')

In [20]:
operating_cost.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   cost_id        3000 non-null   object
 1   branch_id      2988 non-null   object
 2   cost_date      3000 non-null   object
 3   cost_category  3000 non-null   object
 4   cost_amount    3000 non-null   float64
dtypes: float64(1), object(4)
memory usage: 117.3+ KB

In [21]:
operating_cost.dtypes

cost_id           object
branch_id         object
cost_date         object
cost_category     object
cost_amount      float64
dtype: object

In [22]:
operating_cost.isnull().sum()

cost_id           0
branch_id        12
cost_date         0
cost_category     0
cost_amount       0
dtype: int64

In [23]:
operating_cost["cost_date"] = pd.to_datetime(operating_cost["cost_date"])

In [24]:
monthly_operating_cost = operating_cost.groupby(operating_cost["cost_date"].dt.to_period("M")
)["cost_amount"].sum()

In [25]:
operating_cost.nunique()

cost_id          3000
branch_id           8
cost_date         722
cost_category       6
cost_amount      2998
dtype: int64

In [26]:
orders.head()

,order_id,order_date,order_time,customer_id,branch_id,order_channel,order_status,gross_sales,discount_amount,net_sales,payment_method
0,O000001,2026-02-18,14:18:00,C05880,B05,Dine-in,Completed,554.85,57.40,497.45,UPI
1,O000002,2025-03-18,19:45:00,C08484,B02,Delivery,Completed,366.00,29.02,336.98,UPI
2,O000003,2026-09-27,18:17:00,C14296,B07,Delivery,Completed,455.20,29.11,426.09,UPI
3,O000004,2026-10-09,13:50:00,C10097,B05,Delivery,Completed,1053.60,78.37,975.23,Cash
4,O000005,2025-07-30,11:34:00,C14756,B05,Takeaway,Completed,252.00,24.54,227.46,Card

In [27]:
orders["order_date"] = pd.to_datetime(orders["order_date"])

In [28]:
orders["order_status"].value_counts()

order_status
Completed    166416
Cancelled      8060
Refunded       5524
Name: count, dtype: int64

In [29]:
orders.groupby("order_status")["net_sales"].agg(["count", "sum"])

               count          sum
order_status
Cancelled       8060   5036193.45
Completed     166416  96739281.18
Refunded        5524   3188858.25

In [30]:
completed_orders = orders[orders["order_status"] == "Completed"]

completed_orders.groupby(
    completed_orders["order_date"].dt.to_period("M")
)["net_sales"].sum()

order_date
2025-01    3713188.02
2025-02    3528484.25
2025-03    3812805.56
2025-04    3659020.27
2025-05    3758481.08
2025-06    3683922.20
2025-07    3714331.52
2025-08    3712383.35
2025-09    3702335.67
2025-10    3777037.43
2025-11    3516533.49
2025-12    3893862.34
2026-01    4228961.81
2026-02    3779708.65
2026-03    4139265.61
2026-04    4048750.37
2026-05    4157016.70
2026-06    4006887.72
2026-07    4672447.66
2026-08    4692363.09
2026-09    4572444.13
2026-10    4767471.57
2026-11    4543141.81
2026-12    4658436.88
Freq: M, Name: net_sales, dtype: float64

In [31]:
monthly_revenue = completed_orders.groupby(
    completed_orders["order_date"].dt.to_period("M")
)["net_sales"].sum()

In [32]:
monthly_comparison = pd.concat(
    [monthly_revenue, monthly_operating_cost],
    axis=1
)

In [33]:
monthly_comparison

          net_sales  cost_amount
2025-01  3713188.02   1746607.12
2025-02  3528484.25   1074222.91
2025-03  3812805.56   1530399.29
2025-04  3659020.27   1681514.97
2025-05  3758481.08   1314402.63
2025-06  3683922.20   1362145.00
2025-07  3714331.52   1541885.79
2025-08  3712383.35   1547051.38
2025-09  3702335.67   1278761.00
2025-10  3777037.43   1482485.45
2025-11  3516533.49   1467757.15
2025-12  3893862.34   1476340.63
2026-01  4228961.81   1322581.80
2026-02  3779708.65   1317456.93
2026-03  4139265.61   1403340.88
2026-04  4048750.37   1416039.77
2026-05  4157016.70   1524628.49
2026-06  4006887.72   1739953.00
2026-07  4672447.66   1849388.36
2026-08  4692363.09   1860408.65
2026-09  4572444.13   1319852.39
2026-10  4767471.57   1555440.46
2026-11  4543141.81   1427986.72
2026-12  4658436.88   1856659.21
2027-01         NaN    103848.97

In [34]:
orders.columns

Index(['order_id', 'order_date', 'order_time', 'customer_id', 'branch_id',
       'order_channel', 'order_status', 'gross_sales', 'discount_amount',
       'net_sales', 'payment_method'],
      dtype='object')

In [35]:
orders.dtypes

order_id                   object
order_date         datetime64[ns]
order_time                 object
customer_id                object
branch_id                  object
order_channel              object
order_status               object
gross_sales               float64
discount_amount           float64
net_sales                 float64
payment_method             object
dtype: object

In [36]:
orders.isnull().sum()

order_id           0
order_date         0
order_time         0
customer_id        0
branch_id          0
order_channel      0
order_status       0
gross_sales        0
discount_amount    0
net_sales          0
payment_method     0
dtype: int64

In [37]:
orders["order_channel"].describe()

count       180000
unique          10
top       Delivery
freq         99955
Name: order_channel, dtype: object

In [38]:
orders["order_channel"].head()

0     Dine-in
1    Delivery
2    Delivery
3    Delivery
4    Takeaway
Name: order_channel, dtype: object

In [39]:
orders["order_channel"].value_counts()

order_channel
Delivery    99955
Dine-in     50410
Takeaway    29523
DELIVERY       27
Dine-In        21
delivery       18
DINE-IN        17
dine-in        14
takeaway       10
TAKEAWAY        5
Name: count, dtype: int64

In [40]:
order_items.head()

  order_item_id order_id product_id  quantity  unit_price
0     OI0000001  O000001       P014         1      311.85
1     OI0000002  O000001       P035         1      119.00
2     OI0000003  O000001       P044         1      124.00
3     OI0000004  O000002       P055         1      366.00
4     OI0000005  O000003       P003         1      220.00

In [41]:
order_items.isnull().sum()

order_item_id    0
order_id         0
product_id       0
quantity         0
unit_price       0
dtype: int64

In [42]:
order_items.dtypes

order_item_id     object
order_id          object
product_id        object
quantity           int64
unit_price       float64
dtype: object

In [43]:
order_items.shape

(376701, 5)

In [44]:
order_items.groupby('product_id')['quantity'].sum()

product_id
P001    8905
P002    9037
P003    9296
P004    9213
P005    9066
P006    9054
P007    9257
P008    8947
P009    9348
P010    8922
P011    9209
P012    9000
P013    9100
P014    9089
P015    9083
P016    9100
P017    8982
P018    8905
P019    9004
P020    9121
P021    8924
P022    9140
P023    9108
P024    9186
P025    9148
P026    9195
P027    8944
P028    9191
P029    9124
P030    8701
P031    9104
P032    8967
P033    9108
P034    9080
P035    9233
P036    9136
P037    8980
P038    9330
P039    9135
P040    9021
P041    9413
P042    9094
P043    9035
P044    9043
P045    9051
P046    9053
P047    9035
P048    8820
P049    9032
P050    9256
P051    9011
P052    9180
P053    9066
P054    8949
P055    8964
P056    9006
Name: quantity, dtype: int64

In [45]:
order_items.nunique()

order_item_id    376700
order_id         180000
product_id           56
quantity              3
unit_price          209
dtype: int64

In [46]:
order_items['order_item_id'].duplicated().sum()

np.int64(1)

In [47]:
order_items['order_item_id'].value_counts()

order_item_id
OI0012346    2
OI0000001    1
OI0251132    1
OI0251140    1
OI0251139    1
            ..
OI0125566    1
OI0125565    1
OI0125564    1
OI0125563    1
OI0376700    1
Name: count, Length: 376700, dtype: int64

In [48]:
completed_order_items = completed_orders.merge(
    order_items,
    on="order_id",
    how="inner"
)

In [49]:
completed_order_items = completed_order_items.merge(
    product,
    on="product_id",
    how="left"
)

In [50]:
product.head()

  product_id    product_name category  selling_price  unit_food_cost
0       P001  Burgers Item 1  Burgers          251.0          121.36
1       P002  Burgers Item 2  Burgers          224.0           97.56
2       P003  Burgers Item 3  BURGERS          220.0           53.00
3       P004  Burgers Item 4  Burgers          220.0          117.00
4       P005  Burgers Item 5  Burgers          295.0           67.09

In [51]:
product.shape

(56, 5)

In [52]:
product.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_id      56 non-null     object
 1   product_name    56 non-null     object
 2   category        56 non-null     object
 3   selling_price   56 non-null     float64
 4   unit_food_cost  56 non-null     float64
dtypes: float64(2), object(3)
memory usage: 2.3+ KB

In [53]:
product.columns

Index(['product_id', 'product_name', 'category', 'selling_price',
       'unit_food_cost'],
      dtype='object')

In [54]:
product.isnull().sum()

product_id        0
product_name      0
category          0
selling_price     0
unit_food_cost    0
dtype: int64

In [55]:
branches.head()

  branch_id  branch_name    city         area opening_date  branch_type
0       B01      Central  Indore      MG Road   2022-01-15      Premium
1       B02  Vijay Nagar  Indore  Vijay Nagar   2022-06-01  High-volume
2       B03      Palasia  Indore      Palasia   2023-02-10      Premium
3       B04          Rau  Indore          Rau   2023-08-20     Standard
4       B05    Scheme 78  Indore    Scheme 78   2024-01-05  High-volume

In [56]:
branches.isnull().sum()

branch_id       0
branch_name     0
city            0
area            0
opening_date    0
branch_type     0
dtype: int64

In [57]:
branches.dtypes

branch_id       object
branch_name     object
city            object
area            object
opening_date    object
branch_type     object
dtype: object

In [58]:
branches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   branch_id     8 non-null      object
 1   branch_name   8 non-null      object
 2   city          8 non-null      object
 3   area          8 non-null      object
 4   opening_date  8 non-null      object
 5   branch_type   8 non-null      object
dtypes: object(6)
memory usage: 516.0+ bytes

In [59]:
completed_order_items["food_cost"] = (
    completed_order_items["unit_food_cost"] *
    completed_order_items["quantity"]
)

In [60]:
completed_order_items[["quantity", "unit_food_cost", "food_cost"]].head()

   quantity  unit_food_cost  food_cost
0         1          120.32     120.32
1         1           59.22      59.22
2         1           52.34      52.34
3         1          186.91     186.91
4         1           53.00      53.00

In [61]:
monthly_food_cost = completed_order_items.groupby(
    completed_order_items["order_date"].dt.to_period("M")
)["food_cost"].sum()

In [62]:
monthly_food_cost

order_date
2025-01    1631915.11
2025-02    1546091.27
2025-03    1682695.16
2025-04    1609445.30
2025-05    1656238.97
2025-06    1622324.73
2025-07    1629379.00
2025-08    1636745.52
2025-09    1626750.91
2025-10    1664685.39
2025-11    1543645.01
2025-12    1719940.86
2026-01    1867010.37
2026-02    1664013.37
2026-03    1831755.73
2026-04    1781945.81
2026-05    1820265.05
2026-06    1765967.76
2026-07    2061919.68
2026-08    2062970.20
2026-09    2016213.72
2026-10    2098562.45
2026-11    2003673.59
2026-12    2046425.48
Freq: M, Name: food_cost, dtype: float64

In [63]:
monthly_comparison = pd.concat(
    [monthly_revenue, monthly_operating_cost, monthly_food_cost],
    axis=1
)

In [64]:
monthly_comparison["food_cost_percentage"] = (
    monthly_comparison["food_cost"] /
    monthly_comparison["net_sales"]
) * 100

In [65]:
monthly_comparison

          net_sales  cost_amount   food_cost  food_cost_percentage
2025-01  3713188.02   1746607.12  1631915.11             43.949164
2025-02  3528484.25   1074222.91  1546091.27             43.817434
2025-03  3812805.56   1530399.29  1682695.16             44.132729
2025-04  3659020.27   1681514.97  1609445.30             43.985690
2025-05  3758481.08   1314402.63  1656238.97             44.066710
2025-06  3683922.20   1362145.00  1622324.73             44.037975
2025-07  3714331.52   1541885.79  1629379.00             43.867355
2025-08  3712383.35   1547051.38  1636745.52             44.088807
2025-09  3702335.67   1278761.00  1626750.91             43.938504
2025-10  3777037.43   1482485.45  1664685.39             44.073839
2025-11  3516533.49   1467757.15  1543645.01             43.896781
2025-12  3893862.34   1476340.63  1719940.86             44.170562
2026-01  4228961.81   1322581.80  1867010.37             44.148197
2026-02  3779708.65   1317456.93  1664013.37             44.024911
2026-03  4139265.61   1403340.88  1831755.73             44.253158
2026-04  4048750.37   1416039.77  1781945.81             44.012242
2026-05  4157016.70   1524628.49  1820265.05             43.787773
2026-06  4006887.72   1739953.00  1765967.76             44.073303
2026-07  4672447.66   1849388.36  2061919.68             44.129326
2026-08  4692363.09   1860408.65  2062970.20             43.964420
2026-09  4572444.13   1319852.39  2016213.72             44.094879
2026-10  4767471.57   1555440.46  2098562.45             44.018353
2026-11  4543141.81   1427986.72  2003673.59             44.103259
2026-12  4658436.88   1856659.21  2046425.48             43.929445
2027-01         NaN    103848.97         NaN                   NaN

In [66]:
monthly_discount = completed_orders.groupby(
    completed_orders["order_date"].dt.to_period("M")
)["discount_amount"].sum()

In [67]:
monthly_discount

order_date
2025-01    324936.13
2025-02    307087.70
2025-03    332149.34
2025-04    318398.73
2025-05    326489.72
2025-06    319407.00
2025-07    325920.63
2025-08    323989.30
2025-09    322351.43
2025-10    329076.67
2025-11    304851.21
2025-12    338030.47
2026-01    366268.54
2026-02    326977.15
2026-03    359584.64
2026-04    352286.73
2026-05    360119.75
2026-06    347696.23
2026-07    406134.99
2026-08    407518.70
2026-09    398092.72
2026-10    416550.33
2026-11    392614.79
2026-12    405339.07
Freq: M, Name: discount_amount, dtype: float64

In [68]:
monthly_comparison = pd.concat(                                                        
    [monthly_revenue, monthly_operating_cost, monthly_food_cost, monthly_discount],
    axis=1
)

In [69]:
monthly_comparison["discount_percentage"] = (       
    monthly_comparison["discount_amount"] /
    monthly_comparison["net_sales"]
) * 100

In [70]:
monthly_comparison

,net_sales,cost_amount,food_cost,discount_amount,discount_percentage
2025-01,3713188.02,1746607.12,1631915.11,324936.13,8.750867
2025-02,3528484.25,1074222.91,1546091.27,307087.70,8.703105
2025-03,3812805.56,1530399.29,1682695.16,332149.34,8.711416
2025-04,3659020.27,1681514.97,1609445.30,318398.73,8.701748
2025-05,3758481.08,1314402.63,1656238.97,326489.72,8.686746
2025-06,3683922.20,1362145.00,1622324.73,319407.00,8.670297
2025-07,3714331.52,1541885.79,1629379.00,325920.63,8.774678
2025-08,3712383.35,1547051.38,1636745.52,323989.30,8.727259
2025-09,3702335.67,1278761.00,1626750.91,322351.43,8.706705
2025-10,3777037.43,1482485.45,1664685.39,329076.67,8.712560
2025-11,3516533.49,1467757.15,1543645.01,304851.21,8.669083
2025-12,3893862.34,1476340.63,1719940.86,338030.47,8.681110
2026-01,4228961.81,1322581.80,1867010.37,366268.54,8.660956
2026-02,3779708.65,1317456.93,1664013.37,326977.15,8.650856
2026-03,4139265.61,1403340.88,1831755.73,359584.64,8.687160
2026-04,4048750.37,1416039.77,1781945.81,352286.73,8.701123
2026-05,4157016.70,1524628.49,1820265.05,360119.75,8.662937
2026-06,4006887.72,1739953.00,1765967.76,347696.23,8.677464
2026-07,4672447.66,1849388.36,2061919.68,406134.99,8.692125
2026-08,4692363.09,1860408.65,2062970.20,407518.70,8.684722
2026-09,4572444.13,1319852.39,2016213.72,398092.72,8.706344
2026-10,4767471.57,1555440.46,2098562.45,416550.33,8.737343
2026-11,4543141.81,1427986.72,2003673.59,392614.79,8.641922
2026-12,4658436.88,1856659.21,2046425.48,405339.07,8.701182
2027-01,NaN,103848.97,NaN,NaN,NaN

In [71]:
delivery[[
    "delivery_fee",
    "delivery_commission",
    "packaging_cost"
]].describe()

        delivery_fee  delivery_commission  packaging_cost
count  100000.000000        100000.000000    99750.000000
mean       49.944714           101.971882       18.022197
std        17.317851            72.057356        5.766115
min        20.000000             8.280000        8.000000
25%        34.930000            47.570000       13.050000
50%        49.940000            84.140000       18.030000
75%        65.020000           137.950000       23.010000
max        80.000000           688.260000       28.000000

In [72]:
delivery[[
    "delivery_fee",
    "delivery_commission",
    "packaging_cost"
]].isna().sum()

delivery_fee             0
delivery_commission      0
packaging_cost         250
dtype: int64

In [73]:
delivery["order_id"].nunique()

100000

In [74]:
delivery["order_id"].count()

np.int64(100000)

In [75]:
completed_delivery = completed_orders.merge(
    delivery,
    on="order_id",
    how="left"
)

In [76]:
completed_delivery[
    [
        "order_id",
        "order_channel",
        "delivery_fee",
        "delivery_commission",
        "packaging_cost"
    ]
].head()

  order_id order_channel  delivery_fee  delivery_commission  packaging_cost
0  O000001       Dine-in           NaN                  NaN             NaN
1  O000002      Delivery         42.93                42.50           25.80
2  O000003      Delivery         32.82                75.48           21.88
3  O000004      Delivery         31.97               210.03           24.30
4  O000005      Takeaway           NaN                  NaN             NaN

In [77]:
completed_delivery_orders = completed_delivery[
    completed_delivery["delivery_fee"].notna()
]

In [78]:
completed_delivery_orders[
    [
        "delivery_fee",
        "delivery_commission",
        "packaging_cost"
    ]
].describe()

       delivery_fee  delivery_commission  packaging_cost
count  92470.000000         92470.000000     92238.00000
mean      49.963193           101.598997        18.02465
std       17.321698            71.826977         5.76850
min       20.000000             8.280000         8.00000
25%       34.952500            47.370000        13.04000
50%       49.950000            83.810000        18.03000
75%       65.040000           137.457500        23.02000
max       80.000000           688.260000        28.00000

In [79]:
monthly_delivery = completed_delivery_orders.groupby(
    completed_delivery_orders["order_date"].dt.to_period("M")
)[[
    "delivery_fee",
    "delivery_commission",
    "packaging_cost"
]].sum()

In [80]:
monthly_delivery

            delivery_fee  delivery_commission  packaging_cost
order_date
2025-01        174904.31            358536.04        62962.60
2025-02        169951.06            343643.69        61001.91
2025-03        184097.44            378409.81        66668.02
2025-04        175123.35            353033.75        62673.69
2025-05        183540.00            358277.06        65887.38
2025-06        175047.56            354814.58        63381.03
2025-07        177649.56            361428.35        64741.63
2025-08        173124.47            359523.96        61905.01
2025-09        178937.58            371703.69        64518.60
2025-10        177201.98            359523.36        63362.65
2025-11        167254.08            335221.81        59554.31
2025-12        182612.57            374391.73        65345.92
2026-01        203095.60            407097.76        72310.59
2026-02        179945.26            369275.61        65647.52
2026-03        202887.22            405217.67        72371.51
2026-04        196790.58            405626.28        70730.15
2026-05        199268.55            398811.89        71420.37
2026-06        191898.13            393234.79        69312.45
2026-07        230282.96            465022.32        82030.55
2026-08        218826.71            456117.31        78945.38
2026-09        218276.40            444152.48        78886.72
2026-10        225345.02            461829.99        82054.95
2026-11        213344.18            437513.90        77937.59
2026-12        220691.85            442451.38        78907.18

In [81]:
monthly_delivery_orders = completed_delivery_orders.groupby(
    completed_delivery_orders["order_date"].dt.to_period("M")
)["order_id"].nunique()

monthly_delivery_orders

order_date
2025-01    3503
2025-02    3411
2025-03    3697
2025-04    3491
2025-05    3660
2025-06    3512
2025-07    3584
2025-08    3480
2025-09    3574
2025-10    3536
2025-11    3313
2025-12    3646
2026-01    4003
2026-02    3635
2026-03    4030
2026-04    3956
2026-05    3971
2026-06    3853
2026-07    4573
2026-08    4383
2026-09    4404
2026-10    4547
2026-11    4272
2026-12    4436
Freq: M, Name: order_id, dtype: int64

In [82]:
monthly_delivery_per_order = monthly_delivery.div(
    monthly_delivery_orders,
    axis=0
)

monthly_delivery_per_order

            delivery_fee  delivery_commission  packaging_cost
order_date
2025-01        49.929863           102.351139       17.973908
2025-02        49.824409           100.745731       17.883879
2025-03        49.796440           102.355913       18.033005
2025-04        50.164237           101.126826       17.952933
2025-05        50.147541            97.889907       18.002016
2025-06        49.842699           101.029208       18.046990
2025-07        49.567400           100.844964       18.064071
2025-08        49.748411           103.311483       17.788796
2025-09        50.066475           104.002152       18.052210
2025-10        50.113682           101.675158       17.919301
2025-11        50.484177           101.183764       17.975946
2025-12        50.085730           102.685609       17.922633
2026-01        50.735848           101.698166       18.064099
2026-02        49.503510           101.588889       18.059840
2026-03        50.344223           100.550290       17.958191
2026-04        49.744838           102.534449       17.879209
2026-05        50.180949           100.431098       17.985487
2026-06        49.804861           102.059380       17.989216
2026-07        50.357087           101.688677       17.938017
2026-08        49.926240           104.065095       18.011723
2026-09        49.563215           100.852062       17.912516
2026-10        49.559054           101.568065       18.045953
2026-11        49.940117           102.414302       18.243818
2026-12        49.750192            99.741069       17.787913

In [83]:
completed_order_items = order_items[
    order_items["order_id"].isin(completed_orders["order_id"])
]

completed_order_items["product_id"].nunique()

56

In [84]:
product_summary = completed_order_items.merge(
    product[
        ["product_id", "product_name", "category", "unit_food_cost"]
    ],
    on="product_id",
    how="left"
)

product_summary["revenue"] = (
    product_summary["quantity"] *
    product_summary["unit_price"]
)

product_summary["food_cost"] = (
    product_summary["quantity"] *
    product_summary["unit_food_cost"]
)

product_summary["profit"] = (
    product_summary["revenue"] -
    product_summary["food_cost"]
)

product_summary = product_summary.groupby(
    ["product_id", "product_name", "category"],
    as_index=False
).agg(
    quantity=("quantity", "sum"),
    revenue=("revenue", "sum"),
    food_cost=("food_cost", "sum"),
    profit=("profit", "sum")
)

product_summary["profit_margin_pct"] = (
    product_summary["profit"] /
    product_summary["revenue"] * 100
)

In [85]:
total_revenue = product_summary["revenue"].sum()
total_profit = product_summary["profit"].sum()

total_revenue, total_profit

(np.float64(105151371.15), np.float64(62560790.71))

In [86]:
product_summary["revenue_contribution_pct"] = (
    product_summary["revenue"] /
    total_revenue * 100
)

product_summary["profit_contribution_pct"] = (
    product_summary["profit"] /
    total_profit * 100
)

In [87]:
product_summary[
    [
        "product_id",
        "product_name",
        "category",
        "revenue",
        "profit",
        "profit_margin_pct",
        "revenue_contribution_pct",
        "profit_contribution_pct"
    ]
].sort_values(
    "profit_contribution_pct",
    ascending=False
).head()

,product_id,product_name,category,revenue,profit,profit_margin_pct,revenue_contribution_pct,profit_contribution_pct
12,P013,Pizza Item 5,Pizza,3297758.80,2330909.80,70.681634,3.136201,3.725832
53,P054,Combos Item 6,Combos,3124809.60,2224365.30,71.184027,2.971725,3.555526
15,P016,Pizza Item 8,Pizza,2660546.20,1909083.28,71.755314,2.530206,3.051565
4,P005,Burgers Item 5,Burgers,2451435.25,1892105.92,77.183598,2.331339,3.024428
48,P049,Combos Item 1,combos,2875761.70,1812925.98,63.041593,2.734878,2.897863

In [88]:
category_summary = product_summary.groupby(
    "category",
    as_index=False
)[
    ["revenue", "profit"]
].sum()

In [89]:
category_summary["profit_margin_pct"] = (
    category_summary["profit"] /
    category_summary["revenue"] * 100
)

category_summary["revenue_contribution_pct"] = (
    category_summary["revenue"] /
    category_summary["revenue"].sum() * 100
)

category_summary["profit_contribution_pct"] = (
    category_summary["profit"] /
    category_summary["profit"].sum() * 100
)

In [90]:
category_summary.sort_values(
    "profit_contribution_pct",
    ascending=False
)

,category,revenue,profit,profit_margin_pct,revenue_contribution_pct,profit_contribution_pct
8,Pizza,17985801.65,11658331.25,64.819636,17.104676,18.635204
4,Combos,19027338.60,9813221.59,51.574326,18.095188,15.685898
7,Main Course,15345451.35,8835403.01,57.576690,14.593677,14.122908
2,Burgers,14318918.40,8582360.09,59.937209,13.617434,13.718433
9,Snacks,10224456.75,6695784.79,65.487927,9.723560,10.702846
6,Desserts,7172184.10,4256351.23,59.345259,6.820818,6.803544
1,Beverages,5972301.00,3575226.99,59.863476,5.679718,5.714805
11,combos,2875761.70,1812925.98,63.041593,2.734878,2.897863
5,DESSERTS,2836269.40,1518045.06,53.522598,2.697320,2.426512
13,pizza,2135408.55,1438005.76,67.341014,2.030795,2.298574
0,BURGERS,1886192.00,1429915.00,75.809621,1.793787,2.285641
3,COMBOS,2759651.10,1343064.57,48.667912,2.624456,2.146815
12,main course,1843309.90,1089918.91,59.128360,1.753006,1.742176
10,beverages,768326.65,512236.48,66.669102,0.730686,0.818782

In [91]:
product_summary["category_clean"] = (
    product_summary["category"]
    .str.strip()
    .str.title()
)

In [92]:
category_summary = product_summary.groupby(
    "category_clean",
    as_index=False
)[["revenue", "profit"]].sum()

In [93]:
category_summary["profit_margin_pct"] = (
    category_summary["profit"] /
    category_summary["revenue"] * 100
)

category_summary["revenue_contribution_pct"] = (
    category_summary["revenue"] /
    category_summary["revenue"].sum() * 100
)

category_summary["profit_contribution_pct"] = (
    category_summary["profit"] /
    category_summary["profit"].sum() * 100
)

In [94]:
category_summary.sort_values(
    "profit_contribution_pct",
    ascending=False
)

,category_clean,revenue,profit,profit_margin_pct,revenue_contribution_pct,profit_contribution_pct
5,Pizza,20121210.20,13096337.01,65.087223,19.135471,20.933778
2,Combos,24662751.40,12969212.14,52.586234,23.454522,20.730576
1,Burgers,16205110.40,10012275.09,61.784677,15.411221,16.004074
4,Main Course,17188761.25,9925321.92,57.743090,16.346683,15.865084
6,Snacks,10224456.75,6695784.79,65.487927,9.723560,10.702846
3,Desserts,10008453.50,5774396.29,57.695190,9.518139,9.230056
0,Beverages,6740627.65,4087463.47,60.639212,6.410404,6.533587

In [95]:
product_summary[
    product_summary["category_clean"] == "Combos"
].sort_values(
    "profit_margin_pct"
)

,product_id,product_name,category,quantity,revenue,food_cost,profit,profit_margin_pct,revenue_contribution_pct,profit_contribution_pct,category_clean
50,P051,Combos Item 3,Combos,8334,2557431.80,1423780.56,1133651.24,44.327721,2.432143,1.812079,Combos
55,P056,Combos Item 8,Combos,8332,3512930.40,1912360.64,1600569.76,45.562239,3.340832,2.558423,Combos
51,P052,Combos Item 4,COMBOS,8479,2759651.10,1416586.53,1343064.57,48.667912,2.624456,2.146815,Combos
54,P055,Combos Item 7,Combos,8313,3027295.80,1553782.83,1473512.97,48.674232,2.878988,2.355330,Combos
52,P053,Combos Item 5,Combos,8444,3521967.35,1802034.04,1719933.31,48.834448,3.349426,2.749219,Combos
49,P050,Combos Item 2,Combos,8606,3282903.65,1621714.64,1661189.01,50.601211,3.122074,2.655320,Combos
48,P049,Combos Item 1,combos,8353,2875761.70,1062835.72,1812925.98,63.041593,2.734878,2.897863,Combos
53,P054,Combos Item 6,Combos,8230,3124809.60,900444.30,2224365.30,71.184027,2.971725,3.555526,Combos

In [96]:
product_summary[
    ["product_id", "product_name", "category_clean",
     "quantity", "revenue", "profit", "profit_margin_pct"]
].sort_values(
    "profit_margin_pct"
).head()

,product_id,product_name,category_clean,quantity,revenue,profit,profit_margin_pct
31,P032,Snacks Item 8,Snacks,8216,1144941.00,483224.36,42.205176
5,P006,Burgers Item 6,Burgers,8404,2194394.10,941189.62,42.890638
22,P023,Main Course Item 7,Main Course,8394,1783225.35,765788.61,42.944018
50,P051,Combos Item 3,Combos,8334,2557431.80,1133651.24,44.327721
19,P020,Main Course Item 4,Main Course,8403,1899445.20,855372.45,45.032752

In [97]:
product_summary[
    [
        "product_id",
        "product_name",
        "category_clean",
        "quantity",
        "revenue",
        "profit",
        "profit_margin_pct",
        "profit_contribution_pct"
    ]
].sort_values(
    "profit_margin_pct"
).head()

,product_id,product_name,category_clean,quantity,revenue,profit,profit_margin_pct,profit_contribution_pct
31,P032,Snacks Item 8,Snacks,8216,1144941.00,483224.36,42.205176,0.772408
5,P006,Burgers Item 6,Burgers,8404,2194394.10,941189.62,42.890638,1.504440
22,P023,Main Course Item 7,Main Course,8394,1783225.35,765788.61,42.944018,1.224071
50,P051,Combos Item 3,Combos,8334,2557431.80,1133651.24,44.327721,1.812079
19,P020,Main Course Item 4,Main Course,8403,1899445.20,855372.45,45.032752,1.367266

In [98]:
total_food_cost = monthly_food_cost.sum()

In [99]:
total_revenue = completed_orders["net_sales"].sum()

total_operating_cost = operating_cost["cost_amount"].sum()

total_profit = (
    total_revenue
    - total_food_cost
    - total_operating_cost
)

profit_margin = (
    total_profit / total_revenue * 100
)

print("Revenue:", total_revenue)
print("Food Cost:", total_food_cost)
print("Operating Cost:", total_operating_cost)
print("Profit:", total_profit)
print("Profit Margin:", profit_margin)

Revenue: 96739281.18
Food Cost: 42590580.440000005
Operating Cost: 36201158.95
Profit: 17947541.79
Profit Margin: 18.55248619907101

In [100]:
monthly_comparison.head()

,net_sales,cost_amount,food_cost,discount_amount,discount_percentage
2025-01,3713188.02,1746607.12,1631915.11,324936.13,8.750867
2025-02,3528484.25,1074222.91,1546091.27,307087.70,8.703105
2025-03,3812805.56,1530399.29,1682695.16,332149.34,8.711416
2025-04,3659020.27,1681514.97,1609445.30,318398.73,8.701748
2025-05,3758481.08,1314402.63,1656238.97,326489.72,8.686746

In [101]:
monthly_comparison.columns

Index(['net_sales', 'cost_amount', 'food_cost', 'discount_amount',
       'discount_percentage'],
      dtype='object')

In [102]:
monthly_comparison["profit"] = (
    monthly_comparison["net_sales"]
    - monthly_comparison["food_cost"]
    - monthly_comparison["cost_amount"]
)

monthly_comparison["profit_margin_pct"] = (
    monthly_comparison["profit"]
    / monthly_comparison["net_sales"]
    * 100
)

In [103]:
monthly_comparison[
    ["profit", "profit_margin_pct"]
]

             profit  profit_margin_pct
2025-01   334665.79           9.012896
2025-02   908170.07          25.738249
2025-03   599711.11          15.728867
2025-04   368060.00          10.058977
2025-05   787839.48          20.961645
2025-06   699452.47          18.986624
2025-07   543066.73          14.620847
2025-08   528586.45          14.238466
2025-09   796823.76          21.522191
2025-10   629866.59          16.676207
2025-11   505131.33          14.364468
2025-12   697580.85          17.914882
2026-01  1039369.64          24.577418
2026-02   798238.35          21.119044
2026-03   904169.00          21.843706
2026-04   850764.79          21.013022
2026-05   812123.16          19.536202
2026-06   500966.96          12.502645
2026-07   761139.62          16.289955
2026-08   768984.24          16.387995
2026-09  1236378.02          27.039762
2026-10  1113468.66          23.355539
2026-11  1111481.50          24.465041
2026-12   755352.19          16.214713
2027-01         NaN                NaN

In [104]:
target_margin = 25

target_profit = total_revenue * target_margin / 100

required_profit_improvement = target_profit - total_profit

target_profit, required_profit_improvement

(np.float64(24184820.295), np.float64(6237278.505000003))

In [105]:
current_food_cost_pct = total_food_cost / total_revenue * 100
current_operating_cost_pct = total_operating_cost / total_revenue * 100

current_total_cost_pct = (
    (total_food_cost + total_operating_cost)
    / total_revenue
    * 100
)

target_total_cost_pct = 100 - target_margin

print("Food Cost %:", current_food_cost_pct)
print("Operating Cost %:", current_operating_cost_pct)
print("Current Total Cost %:", current_total_cost_pct)
print("Target Total Cost %:", target_total_cost_pct)

Food Cost %: 44.02614937850627
Operating Cost %: 37.42136442242272
Current Total Cost %: 81.44751380092899
Target Total Cost %: 75

In [106]:
product_summary["profit"].sum() / product_summary["revenue"].sum() * 100

np.float64(59.49593431430969)

In [107]:
delivery[[
    "delivery_fee",
    "delivery_commission",
    "packaging_cost"
]].describe()

        delivery_fee  delivery_commission  packaging_cost
count  100000.000000        100000.000000    99750.000000
mean       49.944714           101.971882       18.022197
std        17.317851            72.057356        5.766115
min        20.000000             8.280000        8.000000
25%        34.930000            47.570000       13.050000
50%        49.940000            84.140000       18.030000
75%        65.020000           137.950000       23.010000
max        80.000000           688.260000       28.000000

In [108]:
delivery[[
    "delivery_fee",
    "delivery_commission",
    "packaging_cost"
]].sum()

delivery_fee            4994471.42
delivery_commission    10197188.18
packaging_cost          1797714.17
dtype: float64

In [109]:

delivery["delivery_status"].value_counts(dropna=False)

delivery_status
Delivered    94005
Failed        3995
Returned      2000
Name: count, dtype: int64